/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROORAPIDITY_BKG
#define ROORAPIDITY_BKG

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooRapidityBkg : public RooAbsPdf {
public:
	RooRapidityBkg() {} ; 
	RooRapidityBkg(const char *name, const char *title,RooAbsReal& _Y,RooAbsReal& _m);
						
	RooRapidityBkg(const RooRapidityBkg& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new RooRapidityBkg(*this,newname); }
	inline virtual ~RooRapidityBkg() { }

	
protected:
	
	RooRealProxy Y ;
	RooRealProxy m ;

	
	Double_t evaluate() const ;
	

	
private:
	
	ClassDef(RooRapidityBkg,1) // Your description goes here...
};

#endif
