#!/bin/sh
#=========================================================================
#=
#= Name      : purge.sh
#=
#= Purpose   : Lo scopo di questo script e' rimuovere quei file temporanei
#=             che vengono creati da molti programmi, come emacs.
#=             
#= Arguments : -r|-R consentono la forma di delete ricorsivo.
#=
#= Files
#=
#= Emacs     : \%*\% \%.*\% \#*\# \#.*\# *~ .*~
#= Rand      : ,* ,.* .ec1 .ek1 .ek1b .es1
#= Backups   : *.bak .*.bak \#*
#= Temp      : *.tmp .*.tmp
#= Garbages  : a.out core
#=             
#= Created  13-NOV-1994   Massimo CARBONI
#=
#=========================================================================
_NVersion="1.0"
_PROGRAM=`basename $0`

#
# parsing
#
recursive=0
if test $# -ge 1; then
  case $1 in
    -test)
      touch \%foo\% \%.foo\% \#foo\# \#.foo\# foo~ .foo~
      touch ,foo ,.foo .ec1 .ek1 .ek1b .es1
      touch foo.bak .foo.bak \#foo
      touch foo.tmp .foo.tmp
      touch a.out core
      exit 0
    ;;
    -[rR])
      recursive=1
      shift
    ;;
  esac
fi
if test $# -eq 0; then
  target=`pwd`
elif test $# -eq 1; then
  target=$1
  shift
else
  echo 'Usage: $_PROGRAM [-R] [target]'
  exit 1
fi

#
# do the job
#
if test $recursive -eq 1; then
  command="find $target -type d -print"
else
  command="echo $target"
fi

/bin/echo "Removing..."
$command | while read dir; do
  cd $dir
  files=`/bin/echo \%*\% \#* *~ .*~ ,* .ec1 .ek1 .ek1b .es1 *.bak .*.bak *.tmp .*.tmp a.out core`
  for file in $files; do
    path="$dir/$file"
    if test -f $path; then
      /bin/echo "   $path"
      /bin/rm -f $path
    fi
  done
done
/bin/echo "Done"
 
exit
