#!/bin/sh

function usage {
    echo "Usage: sendsms [-a \"list of name\"] <\"telephone numbers\"> <\"message\">"
    echo "Note: use \n for new line"
    exit 1
}

function sendthesms {
# calcola la lunghezza del account mail
#FROM_LENG=`cat ~/.msmtprc | grep from | awk '{print $2}' | wc -c`
FROM_LENG=`echo roberto.covarelli@cern.ch | wc -c`
# lunghezza del messaggio sms
SMS_LENG=`echo -e $2 | wc -c`
let TOT_LENG=SMS_LENG+FROM_LENG
SERVICE_SMS='sms.switch.ch'
SMS=`echo -e "$2"`

# fintanto che il messaggio e' piu' lungo di 160
# char fai il loop

# lunghezza massima del sms
let LENG=160-FROM_LENG
let TOT_SMS=TOT_LENG/LENG+1

smsNb=0
while [ $TOT_LENG -gt 160  ]
do
  let smsNb=smsNb+1
  # spedisci i primi LENG caratteri per sms
  echo "`echo \"($smsNb/$TOT_SMS) ${SMS}\" | head -c ${LENG}`"  | mail -s " " ${1}@${SERVICE_SMS}
  echo "`echo \"($smsNb/$TOT_SMS) ${SMS}\" | head -c ${LENG}`" | tee -a ~/.my_sms   
  # setta la nuova lunghezza del sms e il nuovo contenuto
  let SMS_LENG=SMS_LENG-LENG+8
  SMS=`echo "${SMS}" | tail -c ${SMS_LENG}`
  let TOT_LENG=SMS_LENG+FROM_LENG
done

let smsNb=smsNb+1
if [ $smsNb -eq $TOT_SMS ] && [ $TOT_SMS -gt 1 ];
    then
    echo "($smsNb/$TOT_SMS) ${SMS}" | mail -s " " ${1}@${SERVICE_SMS}
    echo "($smsNb/$TOT_SMS) ${SMS}" | tee -a ~/.my_sms 
else
    echo "${SMS}" | mail -s " " ${1}@${SERVICE_SMS}
   echo "${SMS}" | tee -a ~/.my_sms
fi
}

[ "${1}" = "-h" ]  && usage 
[ -z "${1}" ]  && usage 
[ -z "${2}" ]  && usage 
[ "${1}" = "-a" ] && [ -z "${3}" ]  && usage 

numbers=$1
sms=`echo "$2"`

if [ "${1}" = "-a" ];
    then
   
    sms=`echo "$3"` 
    for name in $2
      do
      number=`more ~/.numtel | awk -F: ' {if (($0) && match(tolower($1),tolower(a))) print $2}' a=$name`
      thename=`more ~/.numtel | awk -F: ' {if (($0) && match(tolower($1),tolower(a))) print $1}' a=$name`
      (date; echo $thename $number) | tee -a ~/.my_sms

      [ "$number" != "" ] && sendthesms $number "$sms"      
      done
else
    for number in $numbers
    do
      (date; echo $number) | tee -a ~/.my_sms
      sendthesms $number "$sms"      
    done
fi
